services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pratiche
      - POSTGRES_PASSWORD= e0Sv;V%iBh&1@Lmu
      - POSTGRES_DB=pratiche_pareri_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
