# Generated by Django 5.2.5 on 2025-08-22 13:14

import concurrency.fields
import datoriLavoro.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoreLavoro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('ragione_sociale', models.CharField(blank=True, max_length=255, verbose_name='Ragione Sociale')),
                ('p_iva', models.CharField(blank=True, max_length=11, validators=[datoriLavoro.models.validate_p_iva_italiana], verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, validators=[datoriLavoro.models.validate_codice_fiscale], verbose_name='Codice Fiscale')),
            ],
            options={
                'verbose_name': 'Datore di Lavoro',
                'verbose_name_plural': 'Datori di Lavoro',
            },
        ),
        migrations.CreateModel(
            name='DatoreLavoroSede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('is_sede_legale', models.BooleanField(default=False, verbose_name='Sede Legale?')),
            ],
            options={
                'verbose_name': 'Sede associata',
                'verbose_name_plural': 'Sedi asscociate',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('nome', models.CharField(default='---', max_length=100)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedi',
            },
        ),
    ]
