# Generated by Django 5.2.5 on 2025-08-19 12:36

import concurrency.fields
import datoriLavoro.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_cityproxy_countryproxy_regionproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoreLavoro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('ragione_sociale', models.CharField(blank=True, max_length=255, verbose_name='Ragione Sociale')),
                ('p_iva', models.CharField(blank=True, max_length=11, validators=[datoriLavoro.models.validate_p_iva_italiana], verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, validators=[datoriLavoro.models.validate_codice_fiscale], verbose_name='Codice Fiscale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datore di Lavoro',
                'verbose_name_plural': 'Datori di Lavoro',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('nome', models.CharField(default='---', max_length=100)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('citta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.cityproxy', verbose_name='Città')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedi',
            },
        ),
        migrations.CreateModel(
            name='DatoreLavoroSede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('is_sede_legale', models.BooleanField(default=False, verbose_name='Sede Legale?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('datore_lavoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datoriLavoro.datorelavoro')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datoriLavoro.sede')),
            ],
            options={
                'verbose_name': 'Sede associata',
                'verbose_name_plural': 'Sedi asscociate',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datorelavoro',
            name='sedi',
            field=models.ManyToManyField(related_name='datori_lavoro', through='datoriLavoro.DatoreLavoroSede', to='datoriLavoro.sede', verbose_name='Sedi'),
        ),
        migrations.AddConstraint(
            model_name='datorelavorosede',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sede_legale', True)), fields=('sede', 'is_sede_legale'), name='unique_legal_office_for_each_sede'),
        ),
        migrations.AlterUniqueTogether(
            name='datorelavorosede',
            unique_together={('datore_lavoro', 'sede')},
        ),
    ]
