# Generated by Django 5.2.5 on 2025-08-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sedi'},
        ),
    ]
