# Generated by Django 5.2.5 on 2025-08-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datorelavoro',
            name='campo_temporaneo',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
