# Generated by Django 5.2.5 on 2025-08-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('datoriLavoro', '0002_alter_sede_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='citta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city', verbose_name='Città'),
        ),
    ]
