# Generated by Django 5.2.5 on 2025-08-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_cityproxy_countryproxy_regionproxy'),
        ('datoriLavoro', '0003_alter_sede_citta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='citta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.cityproxy', verbose_name='Città'),
        ),
    ]
