# Generated by Django 5.2.5 on 2025-08-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0003_datorelavoro_campo_temporaneo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datorelavoro',
            name='campo_temporaneo',
        ),
    ]
