# Generated by Django 5.2.5 on 2025-08-13 12:16

import concurrency.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0004_alter_sede_citta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoreLavoro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('ragione_sociale', models.CharField(blank=True, max_length=255, verbose_name='Ragione Sociale')),
                ('p_iva', models.CharField(blank=True, max_length=11, verbose_name='Partita IVA/Codice Fiscale')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('sedi', models.ManyToManyField(to='datoriLavoro.sede', verbose_name='Sedi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datore di Lavoro',
                'verbose_name_plural': 'Datori di Lavoro',
            },
        ),
    ]
