# Generated by Django 5.2.5 on 2025-08-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_cityproxy_countryproxy_regionproxy'),
        ('datoriLavoro', '0005_datorelavoro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='citta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.cityproxy', verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nome',
            field=models.CharField(default='---', max_length=100),
        ),
    ]
