# Generated by Django 5.2.5 on 2025-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0006_alter_sede_citta_alter_sede_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
