# Generated by Django 5.2.5 on 2025-08-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0007_alter_sede_indirizzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datorelavoro',
            name='p_iva',
            field=models.CharField(blank=True, max_length=11, verbose_name='Partita IVA'),
        ),
    ]
