# Generated by Django 5.2.5 on 2025-08-13 12:28

import datoriLavoro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0008_alter_datorelavoro_p_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datorelavoro',
            name='p_iva',
            field=models.CharField(blank=True, max_length=11, validators=[datoriLavoro.models.validate_p_iva_italiana], verbose_name='Partita IVA'),
        ),
    ]
