# Generated by Django 5.2.5 on 2025-08-13 12:39

import datoriLavoro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoriLavoro', '0009_alter_datorelavoro_p_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datorelavoro',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, validators=[datoriLavoro.models.validate_codice_fiscale], verbose_name='Codice Fiscale'),
        ),
    ]
