# Generated by Django 5.2.5 on 2025-08-21 21:06

import concurrency.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspertoRadioprotezione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('numero_iscrizione', models.CharField(help_text='Inserisci un valore numerico di 5 cifre.', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Assicurati che il numero di iscrizione contenga esattamente 5 cifre.')], verbose_name='Numero di iscrizione')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Nome e Cognome')),
            ],
            options={
                'verbose_name': 'Esperto di Radioprotezione',
                'verbose_name_plural': 'Esperti di Radioprotezione',
            },
        ),
        migrations.CreateModel(
            name='TipoOrigine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name="nome dell'ente")),
            ],
            options={
                'verbose_name': 'Ente inviante',
                'verbose_name_plural': 'Enti invianti',
            },
        ),
        migrations.CreateModel(
            name='TipoPratica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'Tipo di pratica',
                'verbose_name_plural': 'Tipi di pratica',
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ancora attivo')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('descrizione', models.TextField(blank=True, max_length=200, null=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'Tipo di processo',
                'verbose_name_plural': 'Tipi di processo',
            },
        ),
    ]
