# Generated by Django 5.2.5 on 2025-08-12 08:58

import concurrency.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('descrizione', models.TextField(blank=True, max_length=200, null=True, verbose_name='descrizione')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo di processo',
                'verbose_name_plural': 'Tipi di processo',
            },
        ),
    ]
