# Generated by Django 5.2.5 on 2025-08-12 11:57

import concurrency.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareri', '0002_tipoprocesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspertoRadioprotezione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by_fullname', models.CharField(blank=True, max_length=150)),
                ('updated_by_fullname', models.CharField(blank=True, max_length=150)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('numero_iscrizione', models.CharField(help_text='Inserisci un valore numerico di 5 cifre.', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Assicurati che il numero di iscrizione contenga esattamente 5 cifre.')], verbose_name='Numero di iscrizione')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Nome e Cognome')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esperto di Radioprotezione',
                'verbose_name_plural': 'Esperti di Radioprotezione',
            },
        ),
    ]
