# Generated by Django 5.2.5 on 2025-08-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareri', '0004_tipopratica'),
    ]

    operations = [
        migrations.AddField(
            model_name='espertoradioprotezione',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoorigine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipopratica',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoprocesso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
