# Generated by Django 5.2.5 on 2025-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareri', '0005_espertoradioprotezione_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espertoradioprotezione',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ancora attivo'),
        ),
        migrations.AlterField(
            model_name='tipoorigine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ancora attivo'),
        ),
        migrations.AlterField(
            model_name='tipopratica',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ancora attivo'),
        ),
        migrations.AlterField(
            model_name='tipoprocesso',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ancora attivo'),
        ),
    ]
