# .github/workflows/ci.yml
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13" # Assicurati che questa sia la versione corretta del tuo progetto
      - uses: pre-commit/action@v3.0.1 # Questo è il nome dell'azione corretto
