# .github/workflows/pre-commit-ci.yml
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13" # Sostituisci con la versione di Python del tuo progetto
      - uses: pre-commit/ci-action@v1.0.0
